### ISSUE TITLE
请问如何在TypeScript中使用？

### ISSUE THREAD

**Issue by yanxiaodi** [kevenfeng/html-to-wxml#1]
感谢作者，请问如何在TypeScript版的小程序中使用？

**Comment by kevenfeng** [comment]
TypeScrpit 编译的时候，可以不编译此插件代码。小程序目前不支持自动编译TypeScrpit，您在查看效果的也是需要将TypeScrpit编译成小程序编辑器可以识别的JavaScript。

**Comment by yanxiaodi** [comment]
我也想尝试这样做，在tsconfig.json中指定exclude该文件不编译它，但因为其他页面中import进来了，导致tsc还是会去找这个文件，因为生成的文件名还是以js为后缀，导致冲突报错了。

**Comment by kevenfeng** [comment]
小程序里面用TypeScrpit些的话，引用别的库也会有这种问题，确实不好处理

**Comment by yanxiaodi** [comment]
我已经解决了，不使用import语句，不用这样的：
`import Html2Json = require('../../lib/htmlToWxml/htmlToWxml');`

而是使用这样的：
```
declare var require: any;
var Html2Json = require('../../lib/htmlToWxml/htmlToWxml');
```

我本来还写了一个d.ts来获取智能感知，但最后还是放弃了。直接declare使用就是了，就是没有智能感知支持。

**Comment by kevenfeng** [comment]
well done

**Comment by yanxiaodi** [comment]
多谢！^_^
